# AuthController

### login

POST https://localhost/murica_api/auth/login
Content-Type: application/x-www-form-urlencoded

id=G1P52N &
password=G1P52N

# UserController

### Get all users

GET https://localhost/murica_api/user/all

### Get user by id (valid)

GET https://localhost/murica_api/user/ADMIN0

### Get user by id (invalid id)

GET https://localhost/murica_api/user/ADMIN

### Get user by id (invalid request)

GET https://localhost/murica_api/user?id=ADMIN0

### Create user (valid)

POST https://localhost/murica_api/user/new
Content-Type: application/x-www-form-urlencoded

id=G1P52N&name=Gipsz%20Odon&email=gipsz.odon%40murica.com&password=G1P52N&birth_date=2003-03-22

### Create user (no id)

POST https://localhost/murica_api/user/new
Content-Type: application/x-www-form-urlencoded

name=Gipsz%20Odon&email=gipsz.odon%40murica.com&password=G1P52N&birth_date=2003-03-22

### Create user (no name)

POST https://localhost/murica_api/user/new
Content-Type: application/x-www-form-urlencoded

id=G1P52N&email=gipsz.odon%40murica.com&password=G1P52N&birth_date=2003-03-22

### Create user (no email)

POST https://localhost/murica_api/user/new
Content-Type: application/x-www-form-urlencoded

id=G1P52N&name=Gipsz%20Odon&password=G1P52N&birth_date=2003-03-22

### Create user (no password)

POST https://localhost/murica_api/user/new
Content-Type: application/x-www-form-urlencoded

id=G1P52N&name=Gipsz%20Odon&email=gipsz.odon%40murica.com&birth_date=2003-03-22

### Create user (no birth date)

POST https://localhost/murica_api/user/new
Content-Type: application/x-www-form-urlencoded

id=G1P52N&name=Gipsz%20Odon&email=gipsz.odon%40murica.com&password=G1P52N
