### welcome (test)

GET https://localhost/murica_api/

### login

POST https://localhost/murica_api/auth/login
Content-Type: application/x-www-form-urlencoded

username = YTWK3B
password = 69696969

### sayhello (test)

POST https://localhost/murica_api/sayhello
x-api-key: 0b8d1835-2fda-4cd0-af11-1f737cec65e0
Content-Type: application/x-www-form-urlencoded

name = Szobonya

### users

GET https://localhost/murica_api/users/

###
