GET http://localhost/murica_api/sayhello?name=Szobonya

###

POST http://localhost/murica_api/sayhello
x-api-key: fa3b2c9c-a96d-48a8-82ad-0cb775dd3e5d
Content-Type: application/x-www-form-urlencoded

name = Szobonya

###

